### PR TITLE
Sort osm stops by distance from gtfs stop

### PR DESCRIPTION
**Pull request by nereocystis**
This patch sorts osm stops by distance from gtfs stop

### CODE REVIEW

**Comment by nereocystis** [comment]
And the comments from the git checkin

sort osm stops by distance from gtfs stops

For each osm stop, use TreeSet to sort all gtfs stops which are
potential matches
The sort is by distance from the osm stop

Also, clean up ReportViewer so that HashMap key and values are
declared, removing the need for casts.

close: #44

**Comment by barbeau** [comment]
@reubot Any thoughts on this PR?

**Comment by nereocystis** [comment]
Sorry, I let this slip through.

I'll give it a try in the next couple of days.

**Comment by barbeau** [comment]
Replaced by https://github.com/CUTR-at-USF/gtfs-osm-sync/pull/51

**Comment by barbeau** [comment]
Thanks @nereocystis!

**Pull request closed without merging**
